### ISSUE TITLE
Flickering scroll bar

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#2481]
I'm not a huge fan of always showing the scroll bar, but it's a little irritating that every time you click on a sample the scroll bar disappears and reappears. Unless there is some more elegant way to prevent the flickering, I would say let's always show it.

https://user-images.githubusercontent.com/4546722/214938626-fac0513a-f320-4119-8f35-684bb0ed903e.mov

**Comment by manojVivek** [comment]
Yeah, setting some `min-height` enough to have the scroll bar should fix the flickering while loading data.

**Comment by brancz** [comment]
Sounds good!

**Comment by manojVivek** [comment]
This is trickier than I imagined.

This is Firefox only behaviour, and it doesn't happen on Chrome/Safari. 

Firefox just flashed the scrollbar once whenever there is a change in the document height (probably to indicate the scroll position). That's what is causing this flicker and unfortunately setting a `min-height` is not helping as well, because the document height changes after the data loads, causing the scroll bar flicker again.

I went through Firefox `about:config` as well, but I don't see any config specific to this. There is a config to keep it always visible but not to disable this flashing.

**Comment by yomete** [comment]
what do you think about this issue @manojVivek? do you think it's worth spending some time on again, or it might have even been fixed with the new design already?

**Comment by manojVivek** [comment]
Just checked on Firefox and it still happens. 

But this is a Firefox-specific behaviour and not a trivial bug. So we can close it if this is not a pressing concern. 

cc: @brancz
