### ISSUE TITLE
Implement cache for debuginfod exists responses

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#3028]
> The user-agent is `polarsignals.com/debuginfodclient/v1` and it is still spamming Arch server. Maybe a little less then before, but still fairly often.

_Originally posted by @Foxboron in https://github.com/parca-dev/parca/issues/2914#issuecomment-1518418276_
            
---

I suspect this is coming from the "ShouldInitiateUpload" code path, which requests debuginfod servers to check if the debuginfo would be available there.

We should implement a cache for the "exists" responses. Even negative results we should cache for an hour or so.

**Comment by brancz** [comment]
Apologies for taking so long @Foxboron. This should be fixed once #3413 is merged.

**Comment by Foxboron** [comment]
Just confirm it's still an issue: The client is still spamming at a rate of 3 times pr second, all with 404 responses.

**Comment by brancz** [comment]
You’re on elfutils irc right? If so I’ll join later today when we roll this out to production to make sure it has the effect we are looking for. Does that sound good?

**Comment by Foxboron** [comment]
Yep! Same nickname everywhere :)
